repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        language: system
      - id: end-of-file-fixer
        language: system
      - id: check-yaml
        language: system
      - id: check-added-large-files
        language: system

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language: system  # Removed language_version

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        language: system
